version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: todo-app

  app:
    build: .
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
      - PORT=5000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
