[project]
name = "todo-backend-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.0",
    "pydantic>=2.12.3",
    "sqlmodel>=0.0.27",
]
